// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NegociacaoAPI.EF;

namespace NegociacaoAPI.Migrations
{
    [DbContext(typeof(NegociacaoContext))]
    partial class NegociacaoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("NegociacaoAPI.Models.Tomador", b =>
                {
                    b.Property<int>("TomadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CPF")
                        .HasColumnType("TEXT");

                    b.HasKey("TomadorId");

                    b.ToTable("tomadores");

                    b.HasData(
                        new
                        {
                            TomadorId = 1,
                            CPF = "987.335.450-65"
                        },
                        new
                        {
                            TomadorId = 2,
                            CPF = "245.546.680-96"
                        },
                        new
                        {
                            TomadorId = 3,
                            CPF = "435.964.560-02"
                        },
                        new
                        {
                            TomadorId = 4,
                            CPF = "940.872.480-11"
                        });
                });

            modelBuilder.Entity("NegociacaoAPI.Models.Tomador", b =>
                {
                    b.OwnsMany("NegociacaoAPI.Models.Divida", "Dividas", b1 =>
                        {
                            b1.Property<int>("DividaId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("DataAtualizacao")
                                .HasColumnType("TEXT");

                            b1.Property<int>("TomadorId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("TEXT");

                            b1.HasKey("DividaId");

                            b1.HasIndex("TomadorId");

                            b1.ToTable("dividas");

                            b1.WithOwner("Tomador")
                                .HasForeignKey("TomadorId");

                            b1.OwnsMany("NegociacaoAPI.Models.Simulacao", "Simulacoes", b2 =>
                                {
                                    b2.Property<int>("SimulacaoId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("DividaId")
                                        .HasColumnType("INTEGER");

                                    b2.HasKey("SimulacaoId");

                                    b2.HasIndex("DividaId");

                                    b2.ToTable("simulacoes");

                                    b2.WithOwner("Divida")
                                        .HasForeignKey("DividaId");

                                    b2.OwnsMany("NegociacaoAPI.Models.Acordo", "Acordos", b3 =>
                                        {
                                            b3.Property<int>("AcordoId")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("INTEGER");

                                            b3.Property<bool>("Ativo")
                                                .HasColumnType("INTEGER");

                                            b3.Property<int>("SimulacaoId")
                                                .HasColumnType("INTEGER");

                                            b3.HasKey("AcordoId");

                                            b3.HasIndex("SimulacaoId");

                                            b3.ToTable("acordos");

                                            b3.WithOwner("Simulacao")
                                                .HasForeignKey("SimulacaoId");

                                            b3.HasData(
                                                new
                                                {
                                                    AcordoId = 1,
                                                    Ativo = true,
                                                    SimulacaoId = 1
                                                },
                                                new
                                                {
                                                    AcordoId = 2,
                                                    Ativo = true,
                                                    SimulacaoId = 2
                                                },
                                                new
                                                {
                                                    AcordoId = 3,
                                                    Ativo = true,
                                                    SimulacaoId = 3
                                                },
                                                new
                                                {
                                                    AcordoId = 4,
                                                    Ativo = true,
                                                    SimulacaoId = 4
                                                });
                                        });

                                    b2.OwnsMany("NegociacaoAPI.Models.Parcela", "Parcelas", b3 =>
                                        {
                                            b3.Property<int>("ParcelaId")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("INTEGER");

                                            b3.Property<int>("NumeroParcela")
                                                .HasColumnType("INTEGER");

                                            b3.Property<int>("SimulacaoId")
                                                .HasColumnType("INTEGER");

                                            b3.Property<decimal>("ValorParcela")
                                                .HasColumnType("TEXT");

                                            b3.Property<DateTime>("VencimentoParcela")
                                                .HasColumnType("TEXT");

                                            b3.HasKey("ParcelaId");

                                            b3.HasIndex("SimulacaoId");

                                            b3.ToTable("parcelamentos");

                                            b3.WithOwner("Simulacao")
                                                .HasForeignKey("SimulacaoId");

                                            b3.HasData(
                                                new
                                                {
                                                    ParcelaId = 1,
                                                    NumeroParcela = 1,
                                                    SimulacaoId = 1,
                                                    ValorParcela = 100m,
                                                    VencimentoParcela = new DateTime(2020, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                                                },
                                                new
                                                {
                                                    ParcelaId = 2,
                                                    NumeroParcela = 1,
                                                    SimulacaoId = 2,
                                                    ValorParcela = 150m,
                                                    VencimentoParcela = new DateTime(2020, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                                                },
                                                new
                                                {
                                                    ParcelaId = 3,
                                                    NumeroParcela = 1,
                                                    SimulacaoId = 3,
                                                    ValorParcela = 170m,
                                                    VencimentoParcela = new DateTime(2020, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                                                },
                                                new
                                                {
                                                    ParcelaId = 4,
                                                    NumeroParcela = 1,
                                                    SimulacaoId = 4,
                                                    ValorParcela = 170m,
                                                    VencimentoParcela = new DateTime(2020, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                                                });
                                        });

                                    b2.HasData(
                                        new
                                        {
                                            SimulacaoId = 1,
                                            DividaId = 1
                                        },
                                        new
                                        {
                                            SimulacaoId = 2,
                                            DividaId = 2
                                        },
                                        new
                                        {
                                            SimulacaoId = 3,
                                            DividaId = 3
                                        },
                                        new
                                        {
                                            SimulacaoId = 4,
                                            DividaId = 4
                                        });
                                });

                            b1.HasData(
                                new
                                {
                                    DividaId = 1,
                                    DataAtualizacao = new DateTime(2020, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                                    TomadorId = 1,
                                    Valor = 1000m
                                },
                                new
                                {
                                    DividaId = 2,
                                    DataAtualizacao = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                                    TomadorId = 2,
                                    Valor = 1500m
                                },
                                new
                                {
                                    DividaId = 3,
                                    DataAtualizacao = new DateTime(2020, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                                    TomadorId = 4,
                                    Valor = 2500m
                                },
                                new
                                {
                                    DividaId = 4,
                                    DataAtualizacao = new DateTime(2020, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                                    TomadorId = 3,
                                    Valor = 2500m
                                });
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
